DROP TABLE IF EXISTS note CASCADE;
DROP TABLE IF EXISTS test CASCADE;
DROP TABLE IF EXISTS studysession CASCADE;
DROP TABLE IF EXISTS personcourse CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS course CASCADE;
