DROP TABLE IF EXISTS Muistiinpano CASCADE;
DROP TABLE IF EXISTS Koe CASCADE;
DROP TABLE IF EXISTS Opiskelusessio CASCADE;
DROP TABLE IF EXISTS Kurssisuoritus CASCADE;
DROP TABLE IF EXISTS Opiskelija CASCADE;
DROP TABLE IF EXISTS Kurssi CASCADE;
