DROP TABLE IF EXISTS Note CASCADE;
DROP TABLE IF EXISTS Test CASCADE;
DROP TABLE IF EXISTS StudySession CASCADE;
DROP TABLE IF EXISTS PersonCourse CASCADE;
DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Course CASCADE;
